model:
  name: RandomForest
  problem_type: classification  
  parameters:
    n_estimators:
      suggest_type: suggest_int
      min: 10
      max: 3000
    max_depth:
      suggest_type: suggest_int
      min: 1
      max: 500
    min_samples_split:
      suggest_type: suggest_int
      min: 2
      max: 50
    min_samples_leaf:
      suggest_type: suggest_int
      min: 1
      max: 50
    criterion:
      suggest_type: suggest_categorical
      choices:
        - "gini"
        - "entropy"
    bootstrap:
      suggest_type: suggest_categorical
      choices:
        - True
        - False
optimization:
  method: optuna  
  n_trials: 5
  cv: 1
  n_iter: 100 # if the total space of paramaters is smaller than n_iter, it's better to use GridSearch rather than RandomSearch
  random_state: 42
  n_jobs: -1
  verbose: 1
  timeout: 3600
  show_progress_bar: True
data:
  train_path: data/train.csv
  test_path: data/test.csv
